name: Debug
on:
  pull_request:
    types: [opened, synchronize, closed]
jobs:
  output-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: staticaland/repo-managed-by-terraform@main
        with:
          jq_selector: ".pull_request"